CREATE DATABASE pizzahut;
USE PIZZAHUT;
-- FIRST IMPORT  SMALL TABLES DIRECTLY WITHOUT CREATING NEW TABLES IN MYSQL
-- WE HAVE IMPORTED SMALL TABLES LIKE PIZZAS AND PIZZA_TYPES
-- FOR THE BIGGER DATASET FIRST CREATE A TABLE ACCORDING TO THE NEED OF DATATYPES
 CREATE TABLE orders(
 order_id INT NOT NULL PRIMARY KEY,
 order_date DATE NOT NULL,
 order_time TIME NOT NULL);
 -- ANOTHER LARGE DATASET SO WE WILL MAKE ANOTHER TABLE HERE
 CREATE TABLE order_details(
 order_details_id INT NOT NULL,
 order_id INT NOT NULL,
 pizza_id VARCHAR(100) NOT NULL,
 quantity INT NOT NULL,
 CONSTRAINT 
             PRIMARY KEY( order_details_id));
-- AFTER CREATING THE TABLE LETS IMPORT THE DATASET TO CONTINUE FURTHER
 
 
 